import { useEffect, useState } from 'react';

const whatsapp = '5804125585388';
const projectData = [
  { id: 'size', name: 'Size Convert', type: 'HERRAMIENTA PARA ESTAMPADOS', visual: 'product-convert', label: 'SIZE\nCONVERT', tag: 'CONVERT', description: 'Ajusta tallas y medidas de cualquier modelo antes de imprimirlo. Ideal para talleres de estampados, uniformes y produccion textil.', details: 'Adapta las medidas de los disenos a cada talla para preparar modelos de uniformes y estampados antes de impresion.', points: ['Cambia medidas de modelos para cada talla', 'Prepara disenos para estampados y uniformes', 'Reduce el trabajo manual antes de imprimir'] },
  { id: 'ciber', name: 'Ciber Control', type: 'GESTION Y CONTROL', visual: 'product-control', label: 'CIBER\nCONTROL', tag: 'ONLINE', description: 'Centraliza la gestion de equipos, actividades y operacion desde un panel que muestra lo importante de un vistazo.', details: 'Ayuda a supervisar la actividad de un espacio de trabajo, organizar equipos y tener una vista clara de la operacion diaria.', points: ['Panel central de control operativo', 'Visualizacion de equipos y actividades', 'Resumen claro para tomar decisiones rapidas'] },
];

function navigate(route) { window.location.hash = route; }
function Brand() { return <a className="brand" href="#/"><span className="brand-mark"><i></i><i></i><i></i></span>NEXO<span>/</span></a>; }
function Header({ projects = false }) { return <header className={`site-header ${projects ? 'page-header' : ''}`}><Brand /><nav className="desktop-nav"><a href="#/#soluciones">Soluciones</a><a href="#/#proceso">Proceso</a><a href="#/#nosotros">Nosotros</a><a className={projects ? 'active-link' : ''} href="#/proyectos">Proyectos</a></nav><a className="header-cta" href="#/#contacto">Hablemos <span>↗</span></a></header>; }

function Chat() { const [open, setOpen] = useState(false); const [messages, setMessages] = useState([{ role: 'bot', text: 'Hola, soy el asistente de Nexo. Puedo orientarte sobre proyectos, licencias y soluciones a medida.' }]); const [draft, setDraft] = useState(''); const answer = (text) => { const value = text.toLowerCase(); if (value.includes('size') || value.includes('talla') || value.includes('estampado')) return 'Size Convert adapta tallas y medidas de modelos para preparar uniformes y estampados antes de imprimirlos.'; if (value.includes('ciber')) return 'Ciber Control centraliza equipos, actividades y el estado de tu operacion en un solo panel.'; if (value.includes('precio') || value.includes('pago')) return 'Cada licencia perpetua cuesta USD 200. El boton de compra te conecta por WhatsApp.'; if (value.includes('licencia') || value.includes('descarga')) return 'Cada producto incluye licencia perpetua, descarga digital y soporte. Puedes revisar sus detalles antes de comprar.'; if (value.includes('soporte')) return 'Cada licencia incluye soporte inicial. El alcance exacto se confirma antes de comprar.'; return 'Podemos crear paginas web, aplicaciones, sistemas de gestion y automatizaciones. Cuentanos que necesitas y te orientaremos.'; }; const send = (text = draft) => { if (!text.trim()) return; setMessages((old) => [...old, { role: 'user', text }, { role: 'bot', text: answer(text) }]); setDraft(''); }; const lastUser = [...messages].reverse().find((item) => item.role === 'user'); return <section className="chat-widget"><div className="chat-panel" hidden={!open}><div className="chat-header"><div><span className="chat-status"></span><p>ASISTENTE NEXO</p><strong>Como podemos ayudarte?</strong></div><button className="chat-close" onClick={() => setOpen(false)}>×</button></div><div className="chat-messages">{messages.map((message, index) => <div key={index} className={`chat-message ${message.role}`}>{message.text}</div>)}</div><div className="chat-options">{['Ver proyectos', 'Precios', 'Proyecto a medida', 'Licencias', 'Soporte', 'Descargas'].map((item) => <button key={item} onClick={() => send(item)}>{item}</button>)}</div><form className="chat-form" onSubmit={(event) => { event.preventDefault(); send(); }}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Escribe tu consulta..." /><button>↑</button></form><a className="chat-whatsapp" target="_blank" rel="noreferrer" href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(`Hola Nexo, necesito informacion sobre: ${lastUser?.text || 'sus proyectos'}`)}`}>Continuar por WhatsApp <span>↗</span></a></div><button className="chat-toggle" onClick={() => setOpen(!open)}><span>Hablemos</span><svg viewBox="0 0 24 24"><path d="M20 11.2a7.6 7.6 0 0 1-8 7.2 8.8 8.8 0 0 1-3.4-.7L4 19l1.3-3.2A6.8 6.8 0 0 1 4 11.2 7.6 7.6 0 0 1 12 4a7.6 7.6 0 0 1 8 7.2Z" /></svg></button></section>; }

function Home() { return <><Header /><main id="inicio"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span></span> Soluciones digitales a medida</p><h1>Tu proxima<br /><em>gran idea</em><br />en movimiento.</h1><p className="hero-text">Disenamos y construimos tecnologia que resuelve problemas reales. Desde una primera idea hasta una plataforma que hace crecer tu negocio.</p><div className="hero-actions"><a className="button button-dark" href="#/#contacto">Cuentanos tu proyecto <span>↗</span></a><a className="text-link" href="#/#soluciones">Ver lo que hacemos <span>↓</span></a></div></div><div className="hero-art"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="hero-shape shape-lime"></div><div className="hero-shape shape-orange"></div><div className="floating-card card-data"><span className="card-icon">↗</span><p>PROYECTO<br />EN CURSO</p><strong>+38%</strong></div><div className="floating-card card-code"><span>&lt;/&gt;</span><p>Hecho para<br />funcionar.</p></div><div className="dot-grid"></div></div><div className="hero-footer"><span>SCROLL PARA EXPLORAR</span><div></div><span>01 / 05</span></div></section><section className="intro-strip"><p>No hacemos productos genericos. <strong>Construimos herramientas que encajan con tu forma de trabajar.</strong></p><div className="strip-symbol">✳</div></section><Services /><Process /><Sectors /><Contact /></main><Footer /><Chat /></>; }
function Services() { const list = [['Software a medida', 'Sistemas de gestion, automatizaciones, paneles internos e integraciones creadas alrededor de tu operacion.'], ['Paginas web que convierten', 'Experiencias digitales rapidas, claras y memorables que ayudan a tu marca a generar oportunidades.'], ['Apps y plataformas', 'Aplicaciones web y moviles listas para escalar, conectar equipos y acercarte a tus clientes.'], ['Diseno y experiencia', 'Identidad visual, interfaces intuitivas y sistemas de diseno para que cada interaccion se sienta natural.']]; return <section className="services section" id="soluciones"><div className="section-heading"><p className="eyebrow"><span></span> Lo que hacemos</p><h2>Una idea puede<br />llegar muy lejos.</h2><p>Combinamos estrategia, diseno y desarrollo para convertir necesidades en resultados medibles.</p></div><div className="service-list">{list.map(([title, text], index) => <article className={`service-item ${index === 1 ? 'featured-service' : ''}`} key={title}><span className="service-number">0{index + 1}</span><div><h3>{title}</h3><p>{text}</p></div><span className="service-arrow">↗</span></article>)}</div></section>; }
function Process() { return <section className="process section" id="proceso"><div className="section-heading compact"><p className="eyebrow"><span></span> Como trabajamos</p><h2>De la pregunta<br />a la respuesta.</h2></div><div className="process-grid">{[['Escuchamos', 'Entendemos tu negocio, las personas y el desafio antes de proponer una solucion.'], ['Enfocamos', 'Definimos una hoja de ruta clara con objetivos, prioridades y alcance realista.'], ['Creamos', 'Disenamos y desarrollamos en ciclos cortos para mantenerte cerca de cada avance.'], ['Impulsamos', 'Lanzamos, medimos y seguimos mejorando contigo cuando el producto ya esta en uso.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>; }
function Sectors() { return <section className="sectors" id="nosotros"><p className="eyebrow"><span></span> Para quienes quieren mas</p><h2>Empresas establecidas.<br /><em>Emprendimientos valientes.</em><br />Equipos con ganas de mejorar.</h2><div className="sector-tags">{['Comercio', 'Servicios', 'Educacion', 'Salud', 'Logistica', 'Fintech'].map((item) => <span key={item}>{item}</span>)}</div></section>; }
function Contact() { return <section className="contact" id="contacto"><div className="contact-blob"></div><p className="eyebrow"><span></span> El primer paso es simple</p><h2>Hagamos que<br />pase.</h2><p className="contact-text">Cuentanos que necesita tu negocio. Te respondemos con una conversacion honesta, no con una propuesta enlatada.</p><a className="button button-lime" target="_blank" rel="noreferrer" href={`https://wa.me/${whatsapp}?text=Hola%20Nexo%2C%20quiero%20hablar%20sobre%20un%20proyecto.`}>Hablar por WhatsApp <span>↗</span></a></section>; }
function Footer() { return <footer><Brand /><p>Ideas que se convierten en impacto.</p><span>2026</span></footer>; }

function ProductCard({ product }) {
  const [expanded, setExpanded] = useState(false);
  const plans = [
    { label: 'Mensual', price: 10, period: '1 mes', note: 'Empieza hoy', benefits: ['Acceso completo al programa', 'Actualizaciones incluidas', 'Soporte inicial'] },
    { label: '6 meses', price: 40, period: '6 meses', note: 'Ahorra USD 20', benefits: ['Acceso completo por 6 meses', 'Actualizaciones incluidas', 'Soporte durante tu plan'] },
    { label: 'Anual', price: 60, period: '1 año', note: 'Ahorra USD 60', featured: true, benefits: ['Acceso completo durante 1 año', 'Actualizaciones prioritarias', 'Soporte incluido durante el plan'] },
  ];
  const message = (text) => `https://wa.me/${whatsapp}?text=${encodeURIComponent(text)}`;
  return <article className={`product-card ${product.id === 'ciber' ? 'control-card' : ''}`}>
    <div className={`product-visual ${product.visual}`}><span>{product.id === 'size' ? '01' : '02'}</span><div className="mini-window"><i></i><i></i><i></i><b>{product.label.split('\n').map((line) => <span key={line}>{line}<br /></span>)}</b><em>{product.tag}</em></div></div>
    <div className="product-content"><p className="product-type">{product.type}</p><h2>{product.name}</h2><p className="product-description">{product.description}</p><div className="launch-promo"><span>OFERTA DE LANZAMIENTO</span><strong>Activa hoy y recibe acceso, actualizaciones y soporte.</strong></div><div className="product-details"><span>Acceso por suscripcion</span><span>Actualizaciones incluidas</span><span>Soporte incluido</span></div><div className="product-actions"><a className="demo-link" target="_blank" rel="noreferrer" href={`#/demo/${product.id}`}>Ver demo <span>↗</span></a><button className="test-buy product-toggle" onClick={() => setExpanded(!expanded)}>Que hace? <span>{expanded ? '↑' : '↓'}</span></button></div><div className="subscription-heading"><span>PLANES PROMOCIONALES</span><b>Elige mas tiempo y ahorra mucho mas.</b></div><div className="subscription-plans">{plans.map((plan) => <a className={`subscription-plan ${plan.featured ? 'recommended' : ''}`} key={plan.label} target="_blank" rel="noreferrer" href={message(`Hola Nexo, quiero suscribirme a ${product.name}. Plan: ${plan.label} (${plan.period}) por USD ${plan.price}.`)}>{plan.featured && <em>MEJOR OFERTA</em>}<span className="plan-name">{plan.label}</span><strong>USD {plan.price}</strong><small>por {plan.period}</small><b className="plan-saving">{plan.note}</b><ul>{plan.benefits.map((benefit) => <li key={benefit}>{benefit}</li>)}</ul><i>Elegir este plan <b>↗</b></i></a>)}</div><a className="perpetual-license" target="_blank" rel="noreferrer" href={message(`Hola Nexo, quiero una cotizacion para licencia permanente de ${product.name}.`)}><span>Necesitas licencia permanente?</span><strong>Solicitar cotizacion <b>↗</b></strong></a>{expanded && <div className="product-expanded"><p><strong>{product.name}</strong> {product.details}</p><ul>{product.points.map((item) => <li key={item}>{item}</li>)}</ul></div>}</div>
  </article>;
}
function Projects() { return <><Header projects /><main><section className="catalog page-catalog"><div className="catalog-heading"><div><p className="eyebrow"><span></span> Proyectos disponibles</p><h1>Soluciones listas<br />para impulsar tu negocio.</h1></div><p>Elige el plan de suscripcion que mejor se adapte a tu negocio. Actualizaciones y soporte incluidos.</p></div><div className="catalog-products">{projectData.map((item) => <ProductCard key={item.id} product={item} />)}</div></section></main><Footer /></>; }

function Notice() { return <div className="demo-notice"><span>DEMO INTERACTIVO · Datos simulados</span><a href="#/proyectos">← Volver a proyectos</a></div>; }
function CiberDemo() { const [tab, setTab] = useState('hours'); const [toast, setToast] = useState(''); const say = (text) => { setToast(text); setTimeout(() => setToast(''), 1800); }; const stations = ['PC 1', 'PC 2', 'PC 4', 'PC 5', 'PS5']; return <><Notice /><header className="app-header"><div><small>CIBERCONTROL KM · ADMINISTRACION</small><h1>CyberLife</h1></div><div className="rate"><small>TASA BCV USD</small><strong>Bs. 76,22 / USD</strong><small>Actualizado: demo</small></div></header><main className="app"><nav className="app-tabs">{[['hours', 'Horas'], ['repairs', 'Reparaciones'], ['sales', 'Ventas e inventario'], ['reports', 'Reportes']].map(([id, label]) => <button className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}>{label}</button>)}</nav>{tab === 'hours' && <section><p className="section-label">CIBER Y CONSOLAS</p><h2>Control de horas</h2><div className="metrics"><div><small>Equipos ocupados</small><strong>2 / 11</strong></div><div><small>Sesiones terminadas hoy</small><strong>1</strong></div><div><small>Total horas hoy</small><strong>USD 10,00</strong></div></div><div className="stations">{stations.map((station, index) => <article className={`station ${index === 2 || index === 3 ? 'busy' : ''}`} key={station}><h3>{station} <span className={`status-dot ${index === 4 ? 'off' : ''}`}></span></h3><p className="status">{index === 2 || index === 3 ? <>Cliente activo<br /><b>03:39:50</b></> : <>Computadora · $1,50/h<br />Disponible</>}</p><button className={index === 2 || index === 3 ? 'charge' : ''} onClick={() => say(index === 2 || index === 3 ? 'Cobro simulado registrado.' : 'Sesion de prueba iniciada.')}>{index === 2 || index === 3 ? 'Finalizar y cobrar' : 'Iniciar tiempo'}</button></article>)}</div></section>}{tab === 'repairs' && <DemoRepairs say={say} />}{tab === 'sales' && <DemoSales say={say} />}{tab === 'reports' && <DemoReports />}</main>{toast && <p className="toast">{toast}</p>}</>; }
function DemoRepairs({ say }) { const orders = [['En diagnostico', 'Laptop Lenovo', 'Ana Perez', 'pending'], ['Esperando repuesto', 'PlayStation 4', 'Carlos M.', 'progress'], ['Lista para entregar', 'PC Gamer', 'Diego R.', 'done']]; return <section><div className="panel-title"><div><p className="section-label">ORDENES DE SERVICIO</p><h2>Reparaciones</h2></div><button className="demo-action" onClick={() => say('Nueva orden abierta en modo demo.')}>+ Nueva orden</button></div><div className="order-grid">{orders.map(([status, name, customer, style]) => <article key={name}><span className={`tag ${style}`}>{status}</span><h3>{name}</h3><p>Cliente: {customer}<br />Servicio de ejemplo</p><button className="demo-action" onClick={() => say(`Orden de ${name} abierta.`)}>Ver orden</button></article>)}</div></section>; }
function DemoSales({ say }) { return <section><div className="panel-title"><div><p className="section-label">PUNTO DE VENTA</p><h2>Ventas e inventario</h2></div><button className="demo-action" onClick={() => say('Nueva venta creada en modo demo.')}>Nueva venta</button></div><div className="sales-layout"><div className="inventory-list">{['Refresco 500 ml', 'Snack salado', 'Recarga de impresiones'].map((item) => <article key={item}><b>{item}</b><span>Disponible</span><button className="demo-action" onClick={() => say(`${item} agregado a la venta.`)}>Agregar</button></article>)}</div><aside className="cart"><small>VENTA ACTUAL</small><p>Refresco 500 ml <b>$1,20</b></p><p>Snack salado <b>$0,80</b></p><hr /><strong>Total <b>USD 2,00</b></strong><button onClick={() => say('Cobro simulado completado.')}>Cobrar venta</button></aside></div></section>; }
function DemoReports() { return <section><p className="section-label">RESUMEN OPERATIVO</p><h2>Reportes</h2><div className="report-grid">{[['Ventas hoy', 'USD 18,50'], ['Horas vendidas', '12 h'], ['Reparaciones', '3']].map(([label, value]) => <article key={label}><small>{label}</small><strong>{value}</strong><span>Datos de ejemplo</span></article>)}</div><div className="demo-card"><b>Actividad de la semana</b><div className="bar-chart">{[36, 58, 44, 75, 63, 91, 52].map((height, index) => <i key={index} style={{ height: `${height}%` }}></i>)}</div></div></section>; }
function SizeDemo() { const [tab, setTab] = useState('transform'); const [sizes, setSizes] = useState([]); const [pieces, setPieces] = useState([]); const [toast, setToast] = useState(''); const toggle = (value, list, setter) => setter(list.includes(value) ? list.filter((item) => item !== value) : [...list, value]); const say = (text) => { setToast(text); setTimeout(() => setToast(''), 1800); }; const labels = ['6', '8', '10', '12', '14', '16', 'S', 'M', 'L', 'XL', 'XXL']; const pieceList = ['Frente', 'Espalda', 'Manga derecha', 'Manga izquierda', 'Cuello', 'Ruedo']; return <><Notice /><div className="size-app"><header className="size-header"><h1>Size Converter</h1><nav className="size-tabs">{[['transform', 'Transformar'], ['sizes', 'Configuracion de tallas'], ['pieces', 'Configuracion de piezas']].map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav></header><main className="size-main">{tab === 'transform' && <section><h2>Conversor de tallas</h2><p>Transforma las piezas PNG de una prenda utilizando las medidas exactas de las tallas configuradas.</p><b>Seleccionar tallas ({sizes.length}/11)</b><div className="size-choices">{labels.map((label) => <button key={label} className={`size-choice ${sizes.includes(label) ? 'selected' : ''}`} onClick={() => toggle(label, sizes, setSizes)}>{label}</button>)}</div><b>Piezas PNG de ejemplo</b><div className="drop-grid">{pieceList.map((piece) => <div className={`drop-zone ${pieces.includes(piece) ? 'active' : ''}`} key={piece} onClick={() => toggle(piece, pieces, setPieces)}><div><strong>↑</strong><b>{piece}</b><span>{pieces.includes(piece) ? 'Pieza seleccionada' : 'Haz clic para seleccionar'}</span></div></div>)}</div><div className="transform-bar"><span>Seleccionadas: {sizes.length} tallas y {pieces.length} piezas.</span><button onClick={() => say('Transformacion simulada completada. El programa completo genera los PNG.')}>Transformar piezas</button></div></section>}{tab === 'sizes' && <SizeSettings say={say} />}{tab === 'pieces' && <PieceSettings say={say} />}</main></div>{toast && <p className="toast">{toast}</p>}</>; }
function SizeSettings({ say }) { return <section><div className="panel-title"><div><h2>Configuracion de tallas</h2><p>Medidas configuradas para los modelos de ejemplo.</p></div><button className="demo-action" onClick={() => say('Nueva talla creada en modo demo.')}>+ Nueva talla</button></div><div className="setting-toolbar"><span>Unidad: <b>Centimetros</b></span><span>DPI: <b>300</b></span><button className="demo-action" onClick={() => say('Parametros abiertos en modo demo.')}>Editar parametros</button></div><div className="config-table"><div className="table-head"><span>Talla</span><span>Ancho</span><span>Alto</span><span>Estado</span><span></span></div>{[['S', '48 cm', '68 cm'], ['M', '52 cm', '72 cm'], ['L', '56 cm', '76 cm'], ['XL', '60 cm', '80 cm']].map(([size, width, height]) => <div key={size}><b>{size}</b><span>{width}</span><span>{height}</span><span className="ok">Activa</span><button className="demo-action" onClick={() => say(`Talla ${size} abierta.`)}>Editar</button></div>)}</div></section>; }
function PieceSettings({ say }) { return <section><div className="panel-title"><div><h2>Configuracion de piezas</h2><p>Piezas configuradas para el modelo de ejemplo.</p></div><button className="demo-action" onClick={() => say('Nueva pieza creada en modo demo.')}>+ Agregar pieza</button></div><div className="piece-config-grid">{[['Frente', '45 cm × 67 cm'], ['Espalda', '45 cm × 67 cm'], ['Manga derecha', '22 cm × 48 cm'], ['Manga izquierda', '22 cm × 48 cm'], ['Cuello', '42 cm × 8 cm'], ['Ruedo', '48 cm × 6 cm']].map(([piece, size]) => <article key={piece}><b>{piece}</b><span>Area de prenda</span><small>{size}</small><button className="demo-action" onClick={() => say(`${piece} abierto en modo demo.`)}>Editar pieza</button></article>)}</div></section>; }

export default function App() { const [route, setRoute] = useState(window.location.hash || '#/'); useEffect(() => { const change = () => setRoute(window.location.hash || '#/'); window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []); if (route === '#/proyectos') return <Projects />; if (route === '#/demo/size') return <SizeDemo />; if (route === '#/demo/ciber') return <CiberDemo />; return <Home />; }
